server:
  port: 8090
  error:
    include:
      message: true

spring:
  application:
    name: rangiffler-gateway

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG
#    org.springframework.boot.autoconfigure: DEBUG

---
spring:
  config:
    activate:
      on-profile: 'local'
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: 'http://127.0.0.1:9000'
grpc:
  client:
    grpcGeoClient:
      address: 'static://localhost:9021'
      negotiationType: PLAINTEXT

rangiffler-client:
  base-uri: 'http://127.0.0.1:3001'
rangiffler-userdata:
  base-uri: 'http://127.0.0.1:9010'

---
spring:
  config:
    activate:
      on-profile: 'docker'
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: 'http://auth.rangiffler.dc:9000'
grpc:
  client:
    grpcGeoClient:
      address: 'static://geo.rangiffler.dc:9021'
      negotiationType: PLAINTEXT

#rangiffler-client:
#  base-uri: 'http://frontend.rangiffler.dc'
#rangiffler-userdata:
#  base-uri: 'http://userdata.rangiffler.dc:8089'
---