server:
  port: 8080
  error:
    include:
      message: true

spring:
  application:
    name: rangiffler-gateway

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG
---
spring:
  config:
    activate:
      on-profile: 'local'
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: 'http://127.0.0.1:9000'
rangiffler-client:
  base-uri: 'http://127.0.0.1:3001'
rangiffler-userdata:
  base-uri: 'http://127.0.0.1:9010'

grpc:
  client:
    grpcCountryClient:
      address: 'static://localhost:9021'
      negotiationType: PLAINTEXT
---
spring:
  config:
    activate:
      on-profile: 'docker'
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: 'http://auth.rangiffler.dc:9000'
rangiffler-client:
  base-uri: 'http://frontend.rangiffler.dc:3001'
rangiffler-userdata:
  base-uri: 'http://userdata.rangiffler.dc:9010'
grpc:
  client:
    grpcCountryClient:
      address: 'http://country.rangiffler.dc:9021'
      negotiationType: PLAINTEXT
---